### ISSUE TITLE
convert raw_demand to signed 32 bit

### ISSUE THREAD

**Issue by fromport** [nonspecialist/pyraven#2]
I have solar and want to use your python code 
However, since the raw_demand value is supposed to go negative as well it needs to be a signed 32 bit value, and currently it is 32 bit unsigned:
When I pull power from the grid:
{'timestamp': '2019-02-05T09:02:14Z', 'raw_demand': 817, 'multiplier': 1, 'divisor': 1000, 'demand': 0.817}
When I put data into the grid:
{'timestamp': '2019-02-06T00:22:32Z', 'raw_demand': 4294967161, 'multiplier': 1, 'divisor': 1000, 'demand': 4294967.161}

Could you please change that to signed ?
Thanks in advance

**Comment by fromport** [comment]
This is the fix:
```
--- raven/raven.py.ORIG 2019-02-06 09:45:37.140036009 -0800
+++ raven/raven.py      2019-02-12 12:43:45.854079336 -0800
@@ -145,6 +145,9 @@

     def instantaneous_demand_handler(self, fragment):
         raw_demand = hex_to_int(fragment.find('Demand').text)
+        #with solar the value can go negative, this raw_demand is signed int, so the conversion - Danny ter Haar Feb 2019
+        if(raw_demand & 0x80000000):
+                raw_demand = -0x100000000 + raw_demand
         multiplier = hex_to_int(fragment.find('Multiplier').text)

         divisor = hex_to_int(fragment.find('Divisor').text)
```

It now displays the negative value correctly:

```
{'timestamp': '2019-02-12T01:46:29Z', 'raw_demand': -1484, 'multiplier': 1, 'divisor': 1000, 'demand': -1.484}
{'timestamp': '2019-02-12T01:46:44Z', 'raw_demand': -1536, 'multiplier': 1, 'divisor': 1000, 'demand': -1.536}
{'timestamp': '2019-02-12T01:46:59Z', 'raw_demand': -1608, 'multiplier': 1, 'divisor': 1000, 'demand': -1.608}
```

**Comment by nonspecialist** [comment]
That's handy, thanks for the fix! I don't get back to this project often, but I'm glad it's useful to others.
